#!/usr/bin/env bash
#
# # Select project directory
# if [[ $# -eq 1 ]]; then
#     selected=$1
# else
#     selected=$(find ~/work/repos ~/dev/repos ~/dev/apps -mindepth 1 -maxdepth 1 -type d | fzf)
# fi
#
# # Exit if no directory is selected
# if [[ -z $selected ]]; then
#     exit 0
# fi
#
# selected_name=$(basename "$selected" | tr . _)
# tmux_running=$(pgrep tmux)
#
# # Start a new tmux session with two tabs if tmux isn't running
# if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
#     tmux new-session -s $selected_name -c $selected -d
#     tmux send-keys -t $selected_name "nvim" C-m
#     tmux new-window -t $selected_name -c $selected
#     tmux attach-session -t $selected_name
#     exit 0
# fi
#
# # Create a new session if it doesn't already exist
# if ! tmux has-session -t=$selected_name 2> /dev/null; then
#     tmux new-session -ds $selected_name -c $selected
#     tmux send-keys -t $selected_name "nvim" C-m
#     tmux new-window -t $selected_name -c $selected
# fi
#
# # Attach to the session if not already attached
# if [[ -z $TMUX ]]; then
#     tmux attach -t $selected_name
# else
#     tmux switch-client -t $selected_name
# fi
#

# Select project directory
if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find ~/work/repos ~/dev/repos ~/dev/apps -mindepth 1 -maxdepth 1 -type d | fzf)
fi

# Exit if no directory is selected
if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)

# Check if session exists, create if not
if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected
    tmux send-keys -t $selected_name "nvim" C-m
    tmux new-window -t $selected_name -c $selected
fi

echo "$selected_name"
